//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAbout
    {
        public int AboutID { get; set; }
        public string AboutTitle { get; set; }
        public string AboutSubtitle { get; set; }
        public string AboutBirthday { get; set; }
        public string AboutWebsite { get; set; }
        public string AboutPhone { get; set; }
        public string AboutCity { get; set; }
        public Nullable<byte> AboutAge { get; set; }
        public string AboutDegree { get; set; }
        public string AboutEmail { get; set; }
        public string AboutFreelance { get; set; }
        public string AboutSubtitle2 { get; set; }
        public string AboutImage { get; set; }
    }
}
