//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblContact
    {
        public int ContactID { get; set; }
        public string ContactSubtitle { get; set; }
        public string ContactAdress { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
    }
}
