//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPortfolio
    {
        public int PortfolioID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSubtitle { get; set; }
        public string ProjectCategory { get; set; }
        public string ProjectImage { get; set; }
    }
}
