//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblResume
    {
        public string ResumeName { get; set; }
        public string ResumeDescription { get; set; }
        public string ResumeAddress { get; set; }
        public string ResumePhone { get; set; }
        public string ResumeMail { get; set; }
        public string ResumeSubDescription { get; set; }
    }
}
